name: Format and Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13
        cache: 'pip'
    
    - name: Install formatter
      run: pip install black==23.12.1

    - name: Check format
      run: black --check . 

    - name: Install dependencies
      run: pip install -r python/requirements.txt

    - name: Run unit tests
      run: python -m unittest tests/unit/*.py

    - name: Run integration tests
      run: python -m unittest tests/integration/*.py
